### ISSUE TITLE
The app doesn't save my username when I refresh the page.

### ISSUE THREAD

**Issue by austinkregel** [nathanheffley/pointer#3]
I'd love it if I never had to re-type my username in! I'd imagine a fake "session" kinda thing can be used if you use `localStorage` to keep track of the username when the loads up the login page 🤔

**Comment by NathanHeffley** [comment]
Good suggestion, I've added this to a PWA project to add this feature when that functionally gets implemented 👍

**Comment by NathanHeffley** [comment]
I see you've already made the changes for storing it locally. I like it; if you make a PR with the change I'll remove this ticket from the PWA project and create a new one for migrating it over instead.

**Comment by austinkregel** [comment]
Yea, I was going to update the tests to make sure I maintain your code quality 😄. I ended up going to bed before I could do that.

**Comment by nathanheffley** [comment]
I resolved this in #36 🎉
